# версия docker-compose
version: '3.8'

# имя директории для хранения данных
volumes:
  postgres_data:
  static_volume:
  media_volume:

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.0-alpine
    # volume и связанная с ним директория в контейнере
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # адрес файла, где хранятся переменные окружения
    env_file:
      - ./foodgram/.env.db
  web:
    image: vostavhy/foodgram_web:latest
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    # "зависит от",
    depends_on:
      - db
    env_file:
      - ./foodgram/.env
  nginx:
    image: vostavhy/foodgram_nginx:latest
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 1337:80
    depends_on:
      - web
